drinkName = {'Beer: Bud Light', 'Beer: Coors Light', 'Beer: Miller Lite',...
        'Beer: Budweiser', 'Beer: Heineken', 'Beer: Light, Other', 'Beer, Other',...
        'Wine: Bordeaux','Wine: Merlot', 'Wine: Pinot Noir', 'Wine: Chardonnay', 'Wine: Other',...
        'Champagne', 'Liquor: Jameson Irish Whiskey', 'Liquor: Jack Daniels',...
        'Liquor: Crown Royal', 'Liquor: Bulleit', 'Liquor: Other',...
        'Vodka: Titos', 'Vodka: Ketel One', 'Vodka: Grey Goose',...
        'Vodka: Absolut', 'Vodka: Smirnoff', 'Vodka: Other',...
        'Rum: Captain Morgan', 'Rum: Bacardi', 'Rum: Goslings', 'Rum: Other',...
        'Tequila: Patrón', 'Tequila: Don Julio', 'Tequila: Corazón',...
        'Tequila: Other', 'Gin: Hendricks', 'Gin: Tanqueray', 'Gin: Other'};
TableAlcValues = table(AlcoholByVolume, mlVol, mlAlc, 'RowNames',drinkName);
PercentAlcohol = [4.2;

mlVol = [

mlAlc = 